name: finexo-project 

on:
  push:  
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Or './public' if your files are in a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
  
